version: "3.9"

services:
  pyeongsaeng-app:
    image: parkparkjihyeon/pyeongsaeng:latest
    container_name: pyeongsaeng-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - S3_IAM_ACCESS_KEY=${S3_IAM_ACCESS_KEY}
      - S3_IAM_SECRET_KEY=${S3_IAM_SECRET_KEY}
      - S3_REGION=${S3_REGION}
      - JWT_SECRET=${JWT_SECRET}
      - KAKAO_CLIENT_ID=${KAKAO_CLIENT_ID}
      - GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY}
      - GOOGLE_GEO_API_KEY=${GOOGLE_GEO_API_KEY}
      - SMS_API_KEY=${SMS_API_KEY}
      - SMS_SECRET_KEY=${SMS_SECRET_KEY}
      - SMS_FROM_NUMBER=${SMS_FROM_NUMBER}
      - ES_HOST=${ES_HOST}
      - ES_PASSWORD=${ES_PASSWORD}
      - ODCLOUD_SERVICE_KEY=${ODCLOUD_SERVICE_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - JAVA_TOOL_OPTIONS=-XX:MaxRAMPercentage=75.0
      - TZ=Asia/Seoul
    networks:
      - pyeongsaeng-net
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - pyeongsaeng-net
    labels:
      logging: "promtail"
      logging_jobname: "nginx"
    depends_on:
      - pyeongsaeng-app
    restart: always

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:latest
    container_name: nginx-exporter
    ports:
      - "9113:9113"
    command: --nginx.scrape-uri=http://nginx:80/stub_status
    depends_on:
      - nginx
    networks:
      - pyeongsaeng-net

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - ./promtail/config.yml:/etc/promtail/docker-config.yml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      - -config.file=/etc/promtail/docker-config.yml
      - -config.expand-env=true
    networks:
      - pyeongsaeng-net

networks:
  pyeongsaeng-net:
    driver: bridge
