spring:
  profiles:
    active: local

  config:
    import: optional:file:.env[.properties]

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            redirect-uri: https://api.pyeongsaeng.site/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            scope: profile_nickname,account_email
            client-name: Kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: 3600000
  refresh-token-expiration: 1209600000

cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET_NAME}
    stack.auto: false
    region.static: ${S3_REGION}
    credentials:
      accessKey: ${S3_IAM_ACCESS_KEY}
      secretKey: ${S3_IAM_SECRET_KEY}

coolsms:
  api-key: ${SMS_API_KEY}
  api-secret: ${SMS_SECRET_KEY}
  from-number: ${SMS_FROM_NUMBER}

google:
  geocoding:
    api-key: ${GOOGLE_GEO_API_KEY}
  maps:
    api-key: ${GOOGLE_MAPS_API_KEY}

elasticsearch:
  host: ${ES_HOST}
  port: 9200
  scheme: http
  username: elastic
  password: ${ES_PASSWORD}

odcloud:
  api:
    base-url: https://api.odcloud.kr/api/nts-businessman/v1/status
    service-key: ${ODCLOUD_SERVICE_KEY}
    return-type: JSON

openai:
  model: gpt-4o
  api:
    key: ${OPENAI_API_KEY}
    url: https://api.openai.com/v1/chat/completions
